apiVersion: v1
description: Deploys Errbit. Errbit is a tool for collecting and managing errors from other applications
name: errbit-helm
version: 0.4.2
sources:
  - https://github.com/tmaier/errbit-helm
  - https://github.com/errbit/errbit
icon: https://errbit.com/images/apps.png
dependencies:
- name: mongodb
  version: ^9.3.1
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  condition: mongodb.enabled
