apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "errbit-helm.fullname" . }}-db-migrate
  labels:
    app: {{ template "errbit-helm.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: {{ template "errbit-helm.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["bundle", "exec", "rake", "db:migrate", "db:mongoid:remove_undefined_indexes", "db:mongoid:create_indexes"]
          envFrom:
            - secretRef:
                name: {{ template "errbit-helm.fullname" . }}
            - configMapRef:
                name: {{ template "errbit-helm.fullname" . }}
          resources:
{{ toYaml .Values.batch.resources | indent 12 }}
      restartPolicy: OnFailure
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
