apiVersion: v1
kind: Secret
metadata:
  name: {{ template "errbit-helm.fullname" . }}
  labels:
    app: {{ template "errbit-helm.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $key, $value := .Values.configSecure }}
  {{ $key | upper }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- if not .Values.mongodb.enabled }}
  MONGODB_PASSWORD: {{ .Values.mongodbPassword | default "" | b64enc | quote -}}
  {{- end }}
